# Configuration for generating website data from the library spreadsheet.

excel:
  file: inputs/library-index.xlsx
  sheet: MAIN
  rows:
    filter: 2
    search: 3
    full_display: 4
    multi_option: 5
    column_headers: 6

documents:
  source_path: example-input-data/documents
  destination_path: outputs/documents
  file_pattern: "**/*"

columns:
  id: ID
  title: Title
  year: Year
  access: Access
  filename: PDF_file_name
  published_url: Published_URL
  status: Portal_Status
  generated:
    display_url: URL
    display_icon: Icon

# Translates the values in the spreadsheet to the values used in the scripts for validation and to provide
# the correct behaviour for the website. For example, the spreadsheet may have "Open" (or some other value to be displayed
# on the website) in the Access column, but the scripts need to use "open" to validate and generate the correct URL and icon.
values:
  access:
    open: Open
    physical_library: Contact us
    publisher: Access via publisher
  status:
    active: Active
    deleted: Delete

website:
  urls:
    download_prefix: /documents/
    physical_library: ""
    contact_us: /#/contact-us
  icons:
    webpage: open_in_new
    download: file_download
    support: contact_support
    library: schedule

general:
  missing_value_token: n/a

query:
  sortings:
    name_asc:
      fields: [Title]
      order: [asc]
    year_name_asc:
      fields: [Year, Title]
      order: [desc, asc]
